stages:
  - build
  - manifest
  - promote

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"
  IMAGE_NAME: andrianey/adguardhomedotdoh
  DOCKER_BUILDKIT: "1"
  TARGET_BRANCH:
    value: "latest"
    options:
      - "latest"
      - "latest-wolfi"
      - "hardened"
      - "hardened-wolfi"
    description: "Branch to promote (latest, latest-wolfi, hardened, hardened-wolfi)"

.docker_setup: &docker_setup
  tags:
    - oracle
  image: docker:24-cli
  services:
    - name: docker:24-dind
  before_script:
    - apk add --no-cache curl jq
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - docker run --privileged --rm tonistiigi/binfmt --install all
    - docker buildx create --use --name dns-builder

build_auto:
  <<: *docker_setup
  stage: build
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == *"wolfi"* ]]; then
        PLATFORMS="linux/amd64,linux/arm64"
      else
        PLATFORMS="linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6"
      fi
      docker buildx build \
        --platform "$PLATFORMS" \
        --provenance=false \
        --no-cache \
        -t $IMAGE_NAME:${CI_COMMIT_BRANCH}-auto \
        --push .
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^(latest|hardened|latest-wolfi|hardened-wolfi)$/'

create_manifest:
  <<: *docker_setup
  stage: manifest
  script:
    - echo "Verifying manifest for $CI_COMMIT_BRANCH"
    - docker buildx imagetools inspect $IMAGE_NAME:${CI_COMMIT_BRANCH}-auto
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^(latest|hardened|latest-wolfi|hardened-wolfi)$/'
  needs: ["build_auto"]

promote_live:
  <<: *docker_setup
  stage: promote
  manual_confirmation: "Are you sure you want to promote $CI_COMMIT_BRANCH to live?"
  script:
    - |
      if [ "$CI_PIPELINE_SOURCE" == "web" ]; then
        SOURCE_TAG="${TARGET_BRANCH}-auto"
        DEST_TAG="${TARGET_BRANCH}"
      else
        SOURCE_TAG="${CI_COMMIT_BRANCH}-auto"
        DEST_TAG="${CI_COMMIT_BRANCH}"
      fi

      echo "Promoting $SOURCE_TAG to $DEST_TAG"

      docker buildx imagetools create \
        -t $IMAGE_NAME:${DEST_TAG} \
        $IMAGE_NAME:${SOURCE_TAG}
    - |
      TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d "{\"username\": \"${DOCKER_HUB_USERNAME}\", \"password\": \"${DOCKER_HUB_PASSWORD}\"}" https://hub.docker.com/v2/users/login/ | jq -r .token)
      
      if [ "$CI_PIPELINE_SOURCE" == "web" ]; then
        DEL_TAG="${TARGET_BRANCH}-auto"
      else
        DEL_TAG="${CI_COMMIT_BRANCH}-auto"
      fi
      
      curl -i -X DELETE -H "Authorization: JWT ${TOKEN}" "https://hub.docker.com/v2/repositories/${IMAGE_NAME}/tags/${DEL_TAG}"
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^(latest|hardened|latest-wolfi|hardened-wolfi)$/'
      when: manual
      allow_failure: false