services:
  adguardhome:
    # Choose your preferred image tag: 'latest' (Alpine) or 'latest-wolfi' (Wolfi)
    image: andrianey/adguardhomedotdoh:latest
    container_name: adguardhome
    hostname: adguardhome
    restart: unless-stopped

    networks:
      adguard_net:
        ipv4_address: 172.172.0.2

    environment:
      - TZ=Asia/Jakarta # Set your timezone

    ports:
      # DNS (Standard & Encrypted)
      - "53:53/tcp"
      - "53:53/udp"
      - "853:853/tcp"
      - "853:853/udp"
      - "5443:5443/tcp"
      - "5443:5443/udp"

      # Web Interface & DoH (HTTP/S)
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp" # Required for HTTP/3 (QUIC)
      - "3000:3000/tcp"
      - "3000:3000/udp"

      # DHCP Server
      - "67:67/udp"
      - "68:68/udp"

      # Development/Profiling
      - "6060:6060/tcp"

    volumes:
      # Core AdGuard Home Data
      - /opt/adguardhome/conf:/opt/adguardhome/conf
      - /opt/adguardhome/work:/opt/adguardhome/work
      # Mount custom SSL certificates resolve over public address https://localhost/dns-query
      # - /opt/adguardhome/certs:/opt/certs

      # Optional: Custom Config Overrides
      # Only mount these if you have custom config files you want to inject
      # - /opt/adguardhome/stubby/stubby.yml:/etc/stubby/stubby.yml:ro
      # - /opt/adguardhome/unbound/unbound.conf:/etc/unbound/unbound.conf:ro

networks:
  adguard_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.172.0.0/24
